[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
maplit = "1.x"
tokio = "1.x"
serde = { version = "1.0", features = ["derive"] }
ldap3 = { version = "0.9.x", default-features = false } # features = ["tls"]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
