[default]
trusted_auth_bearer = "aa"
log_dir = "/tmp"

[default.cas]
prefix_url = "https://cas-test.univ-paris1.fr/cas"

[default.ldap]
url = "ldap://localhost:2389"
bind_dn = "cn=Manager,dc=nodomain"
bind_password = "secret"
base_dn = "dc=nodomain"
groups_dn = "ou=groups,dc=nodomain"
group_object_classes = [ "up1SyncGroup", "groupOfNames", "supannGroupe" ]
stem_object_classes = [ "up1SyncGroup", "organizationalRole" ] # root stem will have up1SyncGroup & organizationalUnit
sgroup_filter = "(objectClass=up1SyncGroup)"

[default.ldap.stem]
filter = "(&(objectClass=up1SyncGroup)(!(objectClass=groupOfNames)))"
#default_separator = "."

#TODO cn = { label = "ID du groupe", description = "l'ID est l'identifiant unique de ce groupe au sein du dossier. Il doit être simple et court, et peut avoir des restrictions de caractères. Une fois créé, il est déconseillé de le modifier." }
[default.ldap.sgroup_attrs.description]
label = "Description"
description = "La description contient des informations sur le groupe, par exemple : ce que le groupe représente, pourquoi il a été créé..."
[default.ldap.sgroup_attrs.ou]
label = "Nom du groupe"
description = "Le nom du groupe, il peut être modifié ultérieurement."
[default.ldap.sgroup_attrs."groupaldOptions;x-glpi"]
label = "Ticket GLPI associé"
input_attrs = { placeholder = "numéro du ticket", inputmode = "number" }
vue_template = """<a target=blank :href='"https://ent.univ-paris1.fr/assistance/" + value'>{{value}}</a>"""
[default.ldap.sgroup_attrs."groupaldOptions;x-comptex-externe-profilename"]
label = "Profils comptex/externe autorisés"
only_in_stem = "collab."
input_attrs = { placeholder = "exemple : {COMPTEX:EXTERNE}auditor {COMPTEX:EXTERNE}orator" }
description = "Identifiants de profils, séparées par des espaces"

# if no "default", "max" est pris
[default.ldap.sgroup_attrs."groupaldOptions;x-member-ttl-max"]
label = "Durée d'appartenance max"
description = "Valeur en jours"
vue_template = "{{value}} jours"
input_attrs = { inputmode = "number" }
[default.ldap.sgroup_attrs."groupaldOptions;x-member-ttl-default"]
label = "Durée d'appartenance par défaut"
description = "Valeur en jours"
vue_template = "{{value}} jours"
input_attrs = { inputmode = "number" }


[default.ldap.groups_flattened_attr]
member = "member"
reader = "supannGroupeLecteurDN"
updater = "supannGroupeAdminDN"
admin = "owner"

# NB: order of "default.ldap.subject_sources" impacts UI subjects ordering

[[default.ldap.subject_sources]]
dn = "ou=admin,dc=nodomain"
name = "Applications"
search_filter = "(|(cn=%TERM%)(displayName=*%TERM%*))"
display_attrs = ["displayName", "description", "cn"]
id_attrs = ["cn"]
vue_template = """<MyIcon name="cogs" /> <span :title='attrs.description'>{{attrs.cn}} - {{attrs.displayName || first_line(attrs.description)}}</span>"""
# default template is "display first non empty attr value"

[[default.ldap.subject_sources]]
dn = "ou=groups,dc=nodomain"
name = "Groupe"
search_filter = "(& (|(cn=*%TERM%*)(ou=*%TERM%*)(description=*%TERM%*)) (objectClass=groupOfNames) )"
display_attrs = ["ou", "description", "cn"]
id_attrs = ["cn"]
# default template is "display first non empty attr value"

[[default.ldap.subject_sources]]
dn = "ou=people,dc=nodomain"
name = "Personnes"
search_filter = "(& (|(uid=%TERM%)(cn=*%TERM%*)(displayName=*%TERM%*)) )" # (!(accountStatus=disabled))
display_attrs = ["displayName", "mail", "eduPersonPrimaryAffiliation", "uid" ]
id_attrs = ["mail", "uid", "eduPersonPrincipalName"]
# below is sent to UI which decide what to do with it. category.attr should be listed in "display_attrs" above
labels = { eduPersonPrimaryAffiliation = { student = "étudiant", staff = "biatss", teacher = "enseignant", _ = "autre" } }
vue_template = """<MyIcon name="user" /> {{ 
    ({ teacher: 'enseignant', student: 'étudiant', staff: 'biatss', researcher: 'chercheur', emeritus: 'professeur émérite', affiliate: 'invité', alum: 'ancien étudiant', retired: 'retraité', 'registered-reader': 'Lecteur externe', 'library-walk-in': 'visiteur bibliothèque' }[attrs.eduPersonPrimaryAffiliation] || 'autre')
  }} - <a target='_blank' :href='"https://annuaire.univ-paris1.fr/ent/" + attrs.mail'>{{attrs.displayName}}</a>"""

[default.remotes.g2t]
periodicity = "12:00"
driver = "mysql"
host = "apogee.univ.fr"
#port = 3306
user = "user"
password = "xxx"
db_name = "g2t"

[default.remotes.foo]
periodicity = "hourly"
driver = "mysql"
host = "apogee.univ.fr"
user = "user"
password = "xxx"
db_name = "foo"