[default]
trusted_auth_bearer = "aa"

[default.cas]
prefix_url = "https://cas-test.univ-paris1.fr/cas"

[default.ldap]
url = "ldap://localhost"
bind_dn = "cn=admin,dc=nodomain"
bind_password = "a"
base_dn = "dc=nodomain"
groups_dn = "ou=groups,dc=nodomain"
group_object_classes = [ "up1SyncGroup", "groupOfNames", "supannGroupe" ]
stem_object_classes = [ "up1SyncGroup", "organizationalRole" ] # root stem will have up1SyncGroup & organizationalUnit

[default.ldap.stem]
filter = "(&(objectClass=up1SyncGroup)(!(objectClass=groupOfNames)))"
#default_separator = "."

[default.ldap.sgroup_attrs]
#TODO cn = { label = "ID du groupe", description = "l'ID est l'identifiant unique de ce groupe au sein du dossier. Il doit être simple et court, et peut avoir des restrictions de caractères. Une fois créé, il est déconseillé de le modifier." }
ou = { label = "Nom du groupe", description = "Le nom du groupe, il peut être modifié ultérieurement." }
description = { label = "Description", description = "La description contient des informations sur le groupe, par exemple : ce que le groupe représente, pourquoi il a été créé..." }

[default.ldap.groups_flattened_attr]
member = "member"
reader = "supannGroupeLecteurDN"
updater = "supannGroupeAdminDN"
admin = "owner"

[[default.ldap.subject_sources]]
dn = "ou=people,dc=nodomain"
name = "Personnes"
search_filter = "(& (|(uid=%TERM%)(cn=*%TERM%*)(displayName=*%TERM%*)) )" # (!(accountStatus=disabled))
display_attrs = ["displayName", "uid"]
vue_template = "{{displayName}}"
vue_template_if_ambiguous = "{{displayName}} ({{uid}})"

[[default.ldap.subject_sources]]
dn = "ou=admin,dc=nodomain"
name = "Applications"
search_filter = "(|(cn=%TERM%)(displayName=*%TERM%*))"
display_attrs = ["displayName", "description", "cn"]
# default template is "display first non empty attr value"

[[default.ldap.subject_sources]]
dn = "ou=groups,dc=nodomain"
name = "Groupe"
search_filter = "(& (|(cn=%TERM%)(ou=*%TERM%*)(description=*%TERM%*)) (objectClass=groupOfNames))"
display_attrs = ["ou", "description", "cn"]
# default template is "display first non empty attr value"

[default.remotes.g2t]
periodicity = "12:00"
driver = "mysql"
host = "apogee.univ.fr"
#port = 3306
user = "user"
password = "xxx"

[default.remotes.foo]
periodicity = "hourly"
driver = "mysql"
host = "apogee.univ.fr"
user = "user"
password = "xxx"
